apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: kube-green
  labels:
    app: admin
    purpose: kube-green-containers
  annotations:
    version: 'latest'
spec:
  selector:
    matchLabels:
      app: admin
  template:
    spec:
      containers:
        - volumeMounts:
            - mountPath: /opt/mw/mount
              name: kube-mount
          name: admin
          ports:
            - containerPort: 8761
              protocol: TCP
              name: kube-port
          imagePullPolicy: IfNotPresent
          image: navikco/admin:latest
          resources:
            requests:
              memory: "150Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "1"
          args: ["green", "admin", "localhost", "30301"]
      volumes:
        - name: kube-mount
          emptyDir: {}
      dnsConfig:
        nameservers:
          - "172.16.32.66"
          - "10.70.241.134"
        searches:
          - "lab.securustech.net"
      restartPolicy: Always
    metadata:
      labels:
        app: admin
  replicas: 1