apiVersion: apps/v1
kind: Deployment
metadata:
  name: referrals-deployment
  namespace: kube-green
  labels:
    app: referrals
    purpose: kube-green-containers
  annotations:
    version: 'latest'
spec:
  selector:
    matchLabels:
      app: referrals
  template:
    spec:
      containers:
        - volumeMounts:
            - mountPath: /opt/mw/mount
              name: referrals
          name: referrals
          ports:
            - containerPort: 8080
              protocol: TCP
              name: kube-port
          imagePullPolicy: IfNotPresent
          image: navikco/referrals:latest
          resources:
            requests:
              memory: "150Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "1"
          args: ["green", "referrals", "10.70.245.142", "30333"]
          volumeMounts:
            - mountPath: "/opt/mw/mount"
              name: kube-mount
      volumes:
        - name: kube-mount
          persistentVolumeClaim:
            claimName: kube-green-nfs
      dnsConfig:
        nameservers:
          - "172.1.1.22"
          - "10.1.1.22"
        searches:
          - "lab.kubeland.net"
      restartPolicy: Always
    metadata:
      labels:
        app: referrals
  replicas: 1