apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: kube-green
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - port: 8761
    nodePort: 30333
    targetPort: 8761
    protocol: TCP
